# .github/dependabot.yml
# Dependabot configuration for HYLASTIX KEYCLOAK PROJECT

version: 2
updates:
  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "HenryKum23"  
    assignees:
      - "HenryKum23"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
    target-branch: "main"

  # Docker dependencies (docker-compose.yml)
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "HenryKum23"
    assignees:
      - "HenryKum23"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "containers"
    # Ignore major version updates for production stability
    ignore:
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]
      - dependency-name: "keycloak"
        update-types: ["version-update:semver-major"]
      - dependency-name: "nginx"
        update-types: ["version-update:semver-major"]

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "HenryKum23"
    assignees:
      - "HenryKum23"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
